# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
# mkdocs.yml
site_name: WRF-ARW installation on AWS using SPACK

# Copyright
copyright: Copyright &copy; 2022 <a href="http://atmosfera.usm.my/" target="_blank">atmosfera.usm.my</a>

# Configuration
theme:
  name: material
  features:
    #- announce.dismiss
    #- content.code.annotate
    #- content.tabs.link
    #- content.tooltips
    #- header.autohide
    #- navigation.expand
    #- navigation.indexes
    #- navigation.instant
    #- navigation.prune
    #- navigation.sections
    #- navigation.tabs
    - navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.follow
    #- toc.integrate

  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# Extensions
markdown_extensions:
  - pymdownx.critic
  - attr_list

plugins:
  - mkdocstrings
  - autorefs
  - search
nav:
  - Create Cluster: index.md
  - Spack Installation: spack.md
  - Intel Compiler Installation: intel_compiler.md
  - NCL Installation: ncl.md
  - WPS Installation: wps.md
  - Testing WRF: test_wrf.md
  - WPS Configuration: wps_configuration.md
  - GEOGRID: geogrid.md
  - UNGRIB: ungrib.md
  - METGRID: metgrid.md
  - Running WRF: run_wrf.md
  - Resources: namelist.md